MVC-Reg-User/MVC-Reg-User/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Reg_User.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC-Reg-User/MVC-Reg-User/Controllers/NewRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Reg_User.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.IO;
using System.Web.Script.Serialization;
using Microsoft.Ajax.Utilities;
using System.Data;

namespace MVC_Reg_User.Controllers
{
    public class NewRegController : Controller
    {
        // GET: NewReg
        database_Access_layer.db dblayer = new database_Access_layer.db();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(UserClass uc, HttpPostedFileBase file)
        {
            string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            string sqlquery = "insert into [dbo].[MVCregUser] (Uname,Uemail,Upwd,Gender,Uimg) values(@Uname,@Uemail,@Upwd,@Gender,@Uimg)";
            SqlCommand sqlcomm = new SqlCommand(sqlquery, sqlconn);
            sqlconn.Open();
            sqlcomm.Parameters.AddWithValue("@Uname", uc.Uname);
            sqlcomm.Parameters.AddWithValue("@Uemail", uc.Uemail);
            sqlcomm.Parameters.AddWithValue("@Upwd", uc.Upwd);
            sqlcomm.Parameters.AddWithValue("@Gender", uc.Gender);
            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("~/User-Images/"), filename);
                file.SaveAs(imgpath);
            }
            sqlcomm.Parameters.AddWithValue("@Uimg", "~/User-Images/" + file.FileName);
            sqlcomm.ExecuteNonQuery();
            sqlconn.Close();
            ViewData["Message"] = "User Record" + uc.Uname + "Đã Lưu Thành Công !";
            return View();
        }
        public ActionResult Home()
        {

            return View();


        }

        public JsonResult get_data()
        {
            DataSet ds = dblayer.Show_Data();
            List<MVCregUser> list = new List<MVCregUser>();
           
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                list.Add(new MVCregUser
                {
                    ID = Convert.ToInt32(dr["ID"]),
                    Uname=dr["Uname"].ToString(),
                    Uemail = dr["Uemail"].ToString(),
                    Upwd = dr["Upwd"].ToString(),
                    Gender = dr["Gender"].ToString(),
                    Uimg = dr["Uimg"].ToString(),
                });
            }
            return Json(new { data = list }, JsonRequestBehavior.AllowGet);
            
        }
    }
}

   
            


  

MVC-Reg-User/MVC-Reg-User/Views/NewReg/Home.cshtml
@model MVC_Reg_User.Models.UserClass
@{
    ViewBag.Title = "NewReg List";
}
<h2>Employee List</h2>
<input id="name" type="text" />
<input id="btnSearch" type="button" value="Tìm Kiếm Tên" />
<table id="employeeTable" class="display" @*style="width:1200px" border="1px"*@>

    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Pass</th>
            <th>Gender</th>
            <th>img</th>
        </tr>
    </thead>
</table>
<link href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
@section scripts{
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

<script>
    //$(function () {
    //    $.get("get_data", {}, function (data) {
    //        var row;
    //        $.each(data, function (i, v1) {
    //            row += "<tr><td>" + v1.Uname + "</td><td>" + v1.Uemail + "</td><td>" + v1.Upwd + "</td><td>" + v1.Gender + "</td><td>" + v1.Uimg + "</td></tr>"
    //        });
    //        $("#employeeTable").append(row);

    //    })
    //})

        //$(document).ready(function myfunction() {
        //    $("#employeeTable").DataTable({
        //        "serverSide": true,
        //        "ajax": {
        //            "url": "/NewReg/get_data",
        //            "type": "POST",
        //            "datatype":"json"
        //        },
        //        "columns": [
        //            { "data": "Uname" },
        //            { "data": "Uemail" },
        //            { "data": "Upwd" },
        //            { "data": "Gender" },
        //            { "data": "Uimg" }
        //        ]


        //    });
        //});
      $("#employeeTable").DataTable({
            "serverSide": true,//gọi đến các hàm khác 
            "paging": false,//phân trang
            "order":false,
            searching: false,//tìm kiếm 
            "ajax": {
                "url": "/NewReg/get_data",
                "type": "POST",
                "datatype": "json",
                "data": function (d) {

                    return $.extend({}, d, {
                        "name": $("#name").val(),

                    });
                }
            },
            "columns": [
                   { "data": "Uname", "name": "Uname" },
                    { "data": "Uemail", "name": "Uemail" },
                    { "data": "Upwd", "name": "Upwd" },
                    { "data": "Gender", "name": "Gender" },
                    { "data": "Uimg", "name": "Uimg" }
            ]
        });


    //    $(document).ready(function myfunction() {
    //        $("#employeeTable").DataTable({
    //            "ajax": {
    //                "url": "/NewReg/Home",
    //                "type": "GET",
    //                "datatype": "json"
    //            },
    //            "success":
    //                [$(function () {
    //                $.get("get_data", {}, function (data) {
    //                    var row;
    //                    $.each(data, function (i, v1) {
    //                        row += "<tr><td>" + v1.Uname + "</td><td>" + v1.Uemail + "</td><td>" + v1.Upwd + "</td><td>" + v1.Gender + "</td><td>" + v1.Uimg + "</td></tr>"
    //                    });
    //                    $("#employeeTable").append(row);

    //                })
    //            })
    //            ]
    //        });
    //});
  



</script>

}

MVC-Reg-User/MVC-Reg-User/Views/NewReg/Index.cshtml
@model MVC_Reg_User.Models.UserClass

@{
    ViewBag.Title = "Index";
}

<h2>Thêm Mới User</h2>


@using (Html.BeginForm("Index", "NewReg",FormMethod.Post,new { enctype="multipart/form-data00"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uemail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uemail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uemail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Upwd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Upwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Upwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Repwd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Repwd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Repwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label("Nam ")
                @Html.RadioButtonFor(model => model.Gender,"N")
                @Html.Label("Nữ ")
                @Html.RadioButtonFor(model => model.Gender,"G")
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uimg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file"/>
          
                @Html.ValidationMessageFor(model => model.Uimg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm Mới " class="btn btn-default" />
            </div>
        </div>
        @Html.ViewData["Message"]
    </div>
}

<div>
    <a href="@Url.Action("Home","NewReg")">Back to list</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}